# Generated by Django 5.2.12 on 2026-05-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
