# Generated by Django 5.2.12 on 2026-05-03 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_project_progress_remove_project_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
